Release Deb Package
pop-os/gnome-shell-extension-popx11gestures pull request #1
Opened 2022-05-16 20:14 UTC by isantop

This PR adds in Deb packaging, which will allow users to download and install the package via Apt. 

Prior to release, this package should be tested for functionality and bugs. Namely, the following testing needs to pass:

* Install deb package `gnome-shell-extension-popx11gestures`
* Enable `COSMIC X11 Gestures` extension
* Ensure that system stability remains unchanged
* Ensure that on systems with multi-touch trackpads supporting at least four fingers, a four-finger up/down swipe correctly changes workspaces, and that the switch animation tracks 1:1 with the gesture input.

2022-05-16 21:46 UTC, linuxgnuru commented
After installing gnome-shell-extension-popx11gestures got the following error:

```/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.popx11gestures.gschema.xml:11:6  Error on line 11 char 6: “<” is not a valid character following the close element name “description”
; the allowed character is “>”.  This entire file has been ignored.
```

2022-05-16 22:03 UTC, linuxgnuru commented
on adding the missing > at the end of the file, tried to enable this but got the following error:

![Screenshot from 2022-05-16 15-59-37](https://user-images.githubusercontent.com/3463589/168689642-fcbe92e2-5575-43aa-89fd-6ef2b89c5ce5.png)

2022-05-16 22:41 UTC, jacobgkau commented
@linuxgnuru I'm seeing it install and enable successfully after the last change to close that XML tag (although it should probably get enabled by default, and it wasn't.)

2022-05-16 22:42 UTC, jacobgkau commented
Actually, getting enabled by default would probably be done in pop-session later: https://github.com/pop-os/session/blob/master_jammy/usr/share/gnome-shell/modes/pop.json

2022-05-16 22:45 UTC, jacobgkau commented
This is what the new package name looks like next to existing Pop extensions:

![Screenshot from 2022-05-16 16-43-53](https://user-images.githubusercontent.com/7199422/168694314-f268ad8f-574a-4ca0-b00a-d3018c8ed711.png)

Is there a reason it's not `gnome-shell-extension-pop-x11-gestures` or at least `gnome-shell-extension-pop-x11gestures`?

2022-05-16 23:08 UTC, isantop commented
@linuxgnuru Adding the `>` itself doesn't fix the schema, you need to recompile the schemas (or update the debpackage, which does that for you).

@jacobgkau 

> Is there a reason it's not gnome-shell-extension-pop-x11-gestures 

The upstream extension is just `x11gestures`, so splitting that up doesn't seem appropriate to me.

> or at least gnome-shell-extension-pop-x11gestures

Originally it was to keep the naming style consistent with the upstream. It can be changed, but we don't currently have guidelines about package names that are expected to be adhered to, so I didn't think it was a huge issue. These generally aren't going to be interacted with by end-users anyway.

2022-05-16 23:09 UTC, isantop commented
Enabling by default is something that should be updated in Pop Session, as those files are controlled by that package rather than the individual extension packages.

2022-05-16 23:12 UTC, jackpot51 commented on popx11gestures@system76.com/src/touchegg/ToucheggClient.js
> +/*
I am somewhat sure this directory needs to be in .gitignore

2022-05-16 23:19 UTC, jacobgkau commented
> Originally it was to keep the naming style consistent with the upstream. It can be changed, but we don't currently have guidelines about package names that are expected to be adhered to, so I didn't think it was a huge issue. These generally aren't going to be interacted with by end-users anyway.

I see the upstream is called `gnome-shell-extension-x11gestures`, it would be nice if we could separate Pop out from the extension name so it's `gnome-shell-extension-pop-x11gestures`. I understand this obviously won't be seen by users very often, but it would be nice to be consistent. I assume it's easier/less risky to change now than after we start shipping it, that's the only reason I brought it up.

2022-05-17 21:12 UTC, linuxgnuru approved these changes
worked without issues. If touchpad is disabled gestures still work but issue with touchegg not this extension

2022-05-18 14:17 UTC, leviport requested changes
Let's get this renamed to `gnome-shell-extension-pop-x11gestures`, as discussed above. John showed me that it's working quite well, so I'd love to see it released soon.

2022-05-18 14:22 UTC, jackpot51 requested changes

2022-05-18 14:22 UTC, jackpot51 commented on popx11gestures@system76.com/COPYRIGHT
> +Copyright (C) 2021 - 2022 José Expósito <jose.exposito89@gmail.com>
Just want to mention again, I think this folder popx11gestures@system76.com should not be checked in, and should be in the .gitignore

2022-05-20 16:22 UTC, linuxgnuru approved these changes
Package was renamed and still functions as it intended (and is buttery smooth)

2022-05-20 16:26 UTC, leviport approved these changes
Approved per John's testing

2022-05-20 20:56 UTC, jackpot51 approved these changes

2022-05-20 20:57 UTC, merged